<?php
  define('CSS_PATH', '/manage_user/app/public/css/');


?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>List User</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="<?= CSS_PATH ?>style.css">
  <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
</head>
<body>
  <?php include(dirname(__DIR__) . '\partial\navbar.phtml'); ?>
  <?php include(dirname(__DIR__) . '\partial\flash.phtml'); ?>
  <h1 class="text-center mt-3">List User</h1>
  <div class="container mt-3">
    <table class="list-user table-striped">
      <thead>
        <tr>
          <th scope="col">No.</th>
          <th scope="col" class="w-20">Profile Picture</th>
          <th scope="col">User</th>
          <th scope="col">Birthday</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        <?php foreach ($param as $key => $user) { ?>
          <tr>
            <th scope="row"><?= $key + 1 ?></th>
            <td class="img-cell"><img src="<?= $user["avatar"] ?>" alt=""></td>
            <td><?= $user["username"] ?></td>
            <td><?= $user["birthday"] ?></td>
            <td>
              <button class="btn btn-info"
                      onclick="location.href='/manage_user/detail?id=<?= urlencode($user['user_id']) ?>'"
              >View Details</button>
            </td>
          </tr>
        <?php } ?>
      </tbody>
    </table>
  </div>
  <?php include(dirname(__DIR__) . '\partial\footer.phtml'); ?>
</body>
</html>