<?php
  define('PUBLIC_PATH', '/manage_user/app/public');
  $isError = $param != null;
?>

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Login</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="<?= PUBLIC_PATH ?>/css/style.css">
  <script defer src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
  <script defer src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  <script defer src="<?= PUBLIC_PATH ?>/js/validateForms.js"></script>
</head>
<body>
  <?php include(dirname(__DIR__) . '\partial\navbar.phtml'); ?>
  
  <div class="container c-form-container">
    <h1 class="text-center">Login</h1>
    
    <form action="/manage_user/login" method="POST" class="validated-form" novalidate>
      <?php include(dirname(__DIR__) . '\partial\flash.phtml'); ?>
      <div class="mb-3">
        <label class="form-label" for="loginName">Username</label>
        <input class="form-control" type="text" id="loginName" autofocus name="loginName" required>
        <div class="invalid-feedback">
          Please enter a username.
        </div>
      </div>
      <div class="mb-3">
        <label class="form-label" for="password">Password</label>
        <input class="form-control" type="password" id="password" name="password" required>
        <div class="invalid-feedback">
          Please enter a username.
        </div>
      </div>
      <button class="btn btn-success">Login</button>
    </form>
  </div>
  
  <?php include(dirname(__DIR__) . '\partial\footer.phtml'); ?>
</body>
</html>

